blues/airnote.live

src/routes/Dashboard/Dashboard.svelte
src/routes/Dashboard/TooltipStates.js

Note: This change also removes the air pressure, which we did because a raw air pressure reading is difficult for the average user to interpret, and that value is still available on the linked safecast dashboard.

feat: show device voltage

---

src/App.svelte

Notehub has a somewhat obscure feature that allows users to configure a dashboard for their projects...
...and then get a link to them with this dashboard link that appears for all devices.
When viewing an Airnote dashboard you must have a `pin` in the URL to change a device’s settings. That pin is included on the URL that’s printed on the physical Airnote enclosure. When viewing an Airnote in Notehub, however, that pin is not present, and users that click that link go to a settings page where they can’t actually change the settings.
This PR redirects users that go to the settings URL, and do not have a pin, to the dashboard where they can view device data.

feat: redirect users w/o a pin to the dashboard instead of settings

---

package-lock.json
package.json
server/server.js
src/routes/Dashboard/Dashboard.svelte

If an Airnote has no recent data we show an error. Previously that error only addressed users with new Airnotes (and therefore had no data yet). This PR adds messaging for Airnote users that previously had data, and do not currently.
Story: https://www.pivotaltracker.com/story/show/181203517
There’s also a small workaround in here, because apparently [`localhost:5000` sometimes doesn’t work on macOS](https://github.com/sveltejs/template/issues/184). That was a fun 30 minutes.

feat: Better error handling for Airnotes with no recent data

---

public/global.css
server/server.js
src/App.svelte
src/components/charts/AQIChart.svelte
src/components/charts/HumidityChart.svelte
src/components/charts/PMChart.svelte
src/components/charts/TempChart.svelte
src/components/charts/VoltageChart.svelte
src/constants.js
src/constants/ErrorTypes.js
src/routes/Dashboard/Dashboard.svelte
src/routes/Dashboard/MapboxMap.svelte
src/routes/Settings/Settings.svelte
src/services/device.js
src/util/errors.js
tests/routes/Dashboard/Dashboard.test.js
tests/routes/Dashboard/Settings.test.js
tests/services/device.test.js

This PR tackles three main problems:
1. Intermittently the dashboard fails to load and gives a white screen of death, which I believe is due to it attempting to render charts before there's data back from Notehub to render the charts with. 
2. The `Unable to fetch device details` error shows in the Settings page when the user has an invalid PIN for the current Airnote device UID. This is confusing and incorrect, if the PIN's invalid, we should show them an indicator of that but still let them view individual Airnote data, just not update it.
3. If a user has an Airnote's device ID, the Settings and Dashboard links should always be visible in the header even if a user has no PIN - they should just not be allowed to be updated unless the correct PIN for a particular Airnote is present.
- …

bug: fix flaky dashboard charts & remove PIN requirements to view settings information

---

cypress/e2e/airnote-pages.spec.cy.js
src/App.svelte
src/services/device.js

The changes to always show the “Settings” link in the UI (https://github.com/blues/airnote.live/commit/a53a9467947c2c82146d2d3f24860f7b5cba1ea0) made it difficult to additionally redirect Notehub users that use the “Dashboard” link that appears on Notehub devices.
This change restores the Notehub redirect, and uses an `"internalNav"` query string parameter to ensure the redirect does _not_ occur to users within the Airnote app itself.
We added two new Cypress tests to verify this functionality.
https://trello.com/c/zC9qnP10/10-remove-unnecessary-redirect-log-on-initial-app-mount

fix: Ensuring Notehub "dashboard" links correctly redirect to Airnote dashbaords

---

src/routes/Settings/Settings.svelte
src/util/errors.js

The links to Notehub are out-of-date. When clicking the link, it shows the events for all devices, not just the user's device.
At the bottom of the settings page, click the link named "View live Airnote events on Notehub.io". If it's working correctly, it should show you Airnote events for just your Airnote.

Update Notehub URLs to latest

---

server/server.js
src/routes/Home/Home.svelte
src/routes/Settings/Settings.svelte
src/routes/Settings/Slider.svelte
src/settingsStore.js

A firmware change requires the `_air_mins` environment variable default settings to be updated.
* Change the default settings for Airnote readings
* Add a check before sending new device env vars to Airnote device to delete env vars that would override project level env vars in Notehub. All other settings updates will go through as usual.
n/a
https://trello.com/c/4yyDtnlM/34-issue-with-airmins-environment-variable

bug: adjust default reading frequency  

---

package.json
src/routes/Dashboard/Dashboard.svelte

A couple of small additions to the Airnote dashboard: add the Notehub device events link already present on the settings page to the dashboard page, and adjust the placement of the Safecast donation banner. 
* Add existing Notehub.io link from the settings page to the dashboard page and insert it underneath the AQI readings and above the map
* Move the "Donate to Safecast" banner from the top of the dashboard page to the bottom of the dashboard
* Add `-y` to scripts to run a local version of the app for development to prevent having to agree to install `concurrently` and `nodemon` each time the app starts up
* https://trello.com/c/w0OZxbDH/21-airnote-dashboard-surface-a-notehubio-events-lin …

feat: add notehub events link to dashboard and move donate banner to bottom of page

---

src/lib/services/device.ts
src/lib/util/url.ts
src/routes/[deviceUID]/+page.svelte

If you use Notehub’s “Dashboard” link you end up going to a URL like `https://airnote.live/dev%3A864475044221348?product=product%3Aorg.airnote.solar.air.v1&pin=`. This caused problems with our redirect logic because the DeviceUID is URL encoded.
This PR adds a new utility function that decodes the pathname.
Open this URL in a private window and ensure it redirects `http://localhost:5173/dev%3A864475044221348?product=product%3Aorg.airnote.solar.air.v1&pin=`. Browse around a little and make sure normal navigation works as expected.

fix: handle for Notehub sending URL encoded DeviceUIDs

---

ops/.gitignore
ops/.terraform.lock.hcl
ops/README.md
ops/prod.tf

DNS for airnote.live start.airnote.live and www.airnote.live were pointing to render.com but we are moving to netlify.com as a web host. 
Create terraform IaC for netlify web site dns. (dmarc records are managed elsewhere)
```
16:48 $ terraform plan
data.aws_route53_zone.airnote-live: Reading...
data.aws_route53_zone.airnote-live: Read complete after 1s [id=Z10280582OPRPH0SJWCVB]
aws_route53_record.cname_www_airnote_live: Refreshing state... [id=Z10280582OPRPH0SJWCVB_www.airnote.live_CNAME]
aws_route53_record.a_airnote_live: Refreshing state... [id=Z10280582OPRPH0SJWCVB_airnote.live_A]
aws_route53_record.cname_start_airnote_live: Refreshing state... [id=Z10280582OPRPH0SJWCVB_start.airnote.live_CNAME]
No changes. Your infrastructure matches the configuration.
Terraform has compared your …
```

feat: move dns from render to netlify

---

package-lock.json
package.json
src/lib/components/analytics.svelte
src/lib/constants.ts
src/routes/+layout.svelte

We want a better understanding of how many users are:
Visiting their dashboard (if at all)
* Frequency of visitation
* Relative frequency vs. Time of Purchase
* Additionally, a larger need of this is to be able to join this data with routing data (through devicename?) general airnote data vs individual airnote data
Add a new `Analytics.svelte` component that will record every time a user lands on the site and changes pages and fire off an event to GA.
Pop that new component into the root `_layout.svelte` file so it's available throughout the whole app.
You can visit the PR link site and at least verify that the GA tag and custom code is there by inspecting the Elements tab in DevTools and searching for `google`.
Any other sorts of …

feat: add google analytics to airnote

---

README.md
src/routes/[deviceUID]/dashboard/MapboxMap.svelte

Now that we’re using Netlify to host our Airnote dashboards, we should create a new Mapbox API token (and deactivate the old one) and move it out of the project and into a Netlify secret env vars.
It’s not a critical secret API key, but it’d be much better to have it out of the public domain in keeping with best practices.
* Make the Mapbox token an env var that gets imported into the `MapboxMap.svelte` file instead of hardcoding it straight into that file.
New env var in Netlify
Tests pass 
n/a
https://trello.com/c/Zpbc4GNv/53-move-mapbox-api-token-to-netlify-protected-env-var

chore: move mapbox api key into env vars

---

cypress/e2e/airnote-pages.spec.cy.ts
src/lib/components/charts/AQIChart.svelte
src/lib/components/charts/HumidityChart.svelte
src/lib/components/charts/PMChart.svelte
src/lib/components/charts/TempChart.svelte
src/lib/components/charts/VoltageChart.svelte
src/lib/constants/DateRangeOptions.ts
src/lib/services/device.ts
src/lib/services/notehub.ts
src/routes/[deviceUID]/dashboard/+page.svelte
src/routes/[deviceUID]/dashboard/Actions.svelte
src/routes/styles.css

Increase the amount of historical data display options for individual device dashboard graphs. We have access to more than just the last 7 days' worth of data. So users should be able to see and download it if they want.
* Adjust charts configs so they can responsively resize based on if their containers get the `maximize-chart` CSS class passed to them.
* Fetch the last 30 days' worth of data for each Airnote device from Notehub, and allow that to be downloaded by the user.
* Change the available date ranges in the dropdown on the dashboard for the charts to 1, 7, 14 and 30 days. When 30 days is selected make the charts adjust to take up a full row to give users a better look at the amount of data points displayed in a 30 day time period. All other time frames the charts should maintain …

feat: increase historical data limits for device dashboards

---

src/lib/services/notehub.ts
src/routes/[deviceUID]/dashboard/+page.svelte
src/routes/[deviceUID]/dashboard/Actions.svelte
src/routes/api/download/+server.ts

Currently the Airnote dashboard only provides CSV downloads of the last 30 days' worth of data for users, even though we store up to the last 90 days' worth of data in Notehub.
* Make `getEvents()` function configurable so it defaults to fetching 30 days' worth of data but can accommodate different data sizes as requested
* Delete client-side `downloadData()` function from `Actions.ts` file and instead make the download button a link that hits the `api/download` route to fetch and download the CSV data server side now
* Create a new `+server.ts` file under the route `api/download` to get all the events associated with a particular device for the past 90 days from Notehub and format that data into a CSV downloaded to the user's local computer afterwards
n/a …

feat: downloadable CSV data readings fetch last 90 days' worth of device data

---

package-lock.json
package.json
src/routes/[deviceUID]/dashboard/+page.server.ts
src/routes/quickstart/+page.ts
svelte.config.js

SvelteKit 2.0 debuted recently so we should change with the times and upgrade our Airnote project to keep pace.
Ran the SvelteKit-provided codemod to update all necessary dependencies to SvelteKit v2 (included deps in package.json, and a few minor code changes to +page.server.ts files)
n/a UI is unchanged
All tests pass
1. Go to deploy preview and add Airnote device UID to URL like `https://deploy-preview-66--airnote-live.netlify.app/dev:864475044215258`
2. Click around on the site and make sure everything loads correctly
3. Settings are visible but not updatable without PIN included
4. Make sure quickstart docs look good
Basically, all current functionality in production version of …

deps: update sveltekit version to v2

---

src/lib/layout/Header.svelte

When on a particular page (Settings, Dashboard, Quickstart), bold the current selection in the nav bar 
* [Conditionally render `active` class](https://sveltebyexample.com/class-and-style-directives/) on nav bar links in `<Header />` component based on what page is currently active, as identified using the Svelte [`page`](https://kit.svelte.dev/docs/modules#$app-stores-page) object.
* Update `<Header />` component CSS to use nesting, including media query nesting (I was in there anyway and seemed like a good time to practice using the new CSS nesting that's now widely supported).
https://github.com/blues/airnote.live/assets/20400845/74aefcfe-1fe9-43ed-84f5-e3555566fcfa
All tests continue to pass.
1. Go to http://localhost:5137. Note …

feat: bold current nav link

---

src/routes/[deviceUID]/dashboard/+page.svelte

We route all Airnote data to a Safecast-maintained Grafana dashboard that users can access at `http://tt.safecast.org/dashboard/note:{deviceUID}`.
We previously included that link in the airnote.live dashboards, but removed it when we added our own graphs.
It was requested we bring the link back, as Grafana allows much more flexibility for viewing data—specifically that it allows greater date rates and to go further back in time.
* Add link to the Safecast Grafana dashboards at the bottom of the Airnote dashboard page
All unit and e2e tests pass locally.
1. Go to http://localhost:5173/dev:864475044215258/dashboard
2. Scroll down to the bottom of the dashboard page
3. See the "View Additional data at Safecast.org" link
4. Click it and …

feat: add safecast grafana link to dashboard

---

src/routes/[deviceUID]/+page.server.ts
src/routes/[deviceUID]/+page.svelte

In the Notehub Airnote project, if you go to a device page and click its Dashboard link (top-right corner) you can visits the device’s dashboard on airnote.live.
The link works, however, after clicking the link you start by seeing the Settings page on airnote.live “flash” for a second before being redirected to the Dashboard.
Since we use this link from Notehub a lot in demos, we should attempt to avoid the flash and have the Dashboard load smoothly.
* Move the redirect logic which previously lived client-side in the app and only ran after the browser page had loaded to the server-side so now it runs and performs the redirect before the browser page has loaded.
Browser on left side is current Airnote site when coming from Notehub, browser on right is "fixed" experience when coming from …

feat: move redirect logic when coming from notehub dashboard from client side to server side

---

src/routes/[deviceUID]/dashboard/+page.svelte
src/routes/styles.css

The link to the Safecast Grafana charts should be accessible on the Airnote dashboard even if the dashboard itself doesn't show any data for debugging purposes.
Move the Grafana links outside of the `{#if}` that keeps the link from rendering if an error state is displayed on the page. Now, all that's needed is for a deviceUID to be present (which should always exist since it's in the URL)
All tests continue to pass.
1. Go to the following URL: http://localhost:5173/dev:865284040097903/dashboard?product=product%3Acom.blues.airnote&pin=
2. See that even though a "no data" error message is shown the Grafana link is still visible
n/a
https://bluesinc.atlassian.net/browse/BLUESDEV-20

chore: make safecast grafana link visible even when dashboard errors

---

src/quickstart/02-unboxing-your-airnote.mdx
src/quickstart/03-airnote-setup.mdx
src/quickstart/04-visit-your-device-dashboard.mdx
src/quickstart/06-faq.mdx

I noticed today while firing up a local instance of Airnote that a bunch of A11y warnings pop up on the quickstart page due to the alt text provided in the mdx files that amounts to "you're being redundant with alt text that includes 'this is an image of ...' because screenreaders already announce it's an image"
* Adjust alt text on quickstart MDX docs to not be redundant with text like "Picture of" or "Image of" or "Screenshot of"
previous warnings during local dev on quickstart docs page
no warnings now on local dev on quickstart docs page
1. Start the local app
2. Go to http://localhost:5173/quickstart
3. Check the terminal where the app is running and see that there's no warnings about A11y screenreaders
Any other sorts of …

docs: fix a11y warning about image alt text already announced as images on screenreaders

---

src/routes/[deviceUID]/DeviceSettings.svelte
src/routes/[deviceUID]/dashboard/+page.svelte

The Safecast pipeline feeding data to the Grafana dashboards is no longer operating. Remove links to the Grafana dashboard from the Airnote site.
* Remove link at the bottom of the Airnote dashboard page that linked to the Grafana dashboard
Live Airnote site (link to Grafana still there)
Update Airnote site (link to Grafana removed)
Test still pass
1. Go to http://localhost:5173/dev:864475044215258/dashboard
2. Scroll to the bottom of the page
3. See that underneath the last chart and Safecast banner there is no longer a link to the Safecast Grafana dashboards
n/a
https://bluesinc.atlassian.net/jira/software/c/projects/BLUESDEV/boards/13?selectedIssue=BLUESDEV-379

chore: remove links to Safecast Grafana dashboards that no longer work

---

src/lib/services/notehub.ts

The Airnote dashboards stopped reporting data, even for devices that have checked in within the last week. Find the cause and fix the issue.
The `getEvents()` function we use to pull Airnote data from Notehub was modified to only return up to 10000 events, however, the query was trying to request 12000.
Back down the query limit to 10000.
No new tests added - the limit changed on Notehub's end without warning, not ours.
1. Go to http://localhost:5173/dev:864475044215258/dashboard
2. See that the dashboard loads correctly and data is shown, and no error occurs
n/a
https://bluesinc.atlassian.net/jira/software/c/projects/BLUESDEV/boards/13?selectedIssue=BLUESDEV-399

bug: reduce number of events query pulls from Notehub at once

---

src/lib/util/url.ts
src/routes/[deviceUID]/+page.server.ts
src/routes/[deviceUID]/+page.svelte
src/routes/[deviceUID]/dashboard/+page.svelte

Users reported that some settings like device name or owner name and contact info weren't displaying on their Airnote dashboards after saving the values in and refreshing the page.
Also, link to view particular Airnote events in Notehub is broken due to change to Notehub URL query params
* Figure out the app's Svelte store (client-side way to hold global state that any part of the app can consume) was not always being properly set / updated after a user saved in new settings and the page was refreshed. Fix it to set those values correctly in the client on page load / refresh.
* Update Notehub link to follow new query params format
Reproduce error:
1. In production, go to Settings page of editable Airnote device (i.e. you need a PIN …

bug: fix how Airnote settings data is saved to Notehub

---

package-lock.json
package.json
src/lib/components/charts/AQIChart.svelte
src/lib/components/charts/HumidityChart.svelte
src/lib/components/charts/PMChart.svelte
src/lib/components/charts/TempChart.svelte
src/lib/components/charts/VoltageChart.svelte
src/lib/services/AirReadingModel.ts
src/lib/services/NotehubEventModel.ts
src/lib/services/device.ts
src/lib/services/notehub.ts
src/lib/util/dates.ts
src/routes/[deviceUID]/dashboard/+page.server.ts
src/routes/[deviceUID]/dashboard/+page.svelte
src/routes/[deviceUID]/dashboard/MapboxMap.svelte
src/routes/api/download/+server.ts

An investigation into the use of our non-standard Notehub APIs has caused issues for the Airnote project, and we need to stabilize it and bring it into alignment with our current v1 APIs if possible.
As I looked into the v0 `getEvents()` query, I decided to have a go with using the (newly enhanced) Notehub JS `getEvents()` function (it has lots more query params to narrow down which events are returned), and by jove it worked well.
* Replace Notehub API v0 `getEvents()` query with official Notehub JS SDK `getEvents()` query.
* Refactor date parsing on frontend to ensure unix timestamp dates from Notehub SDK are interpreted correctly (as opposed to ISO dates which came from v0 API)
Site appearance remains unchanged.
All tests pass 
1. …

chore: swap out v0 get events API call for v1

---

src/lib/services/notehub.ts

Add some extra insurance to prevent bad actors from submitting non-Airnote device UIDs to the Notehub API endpoints the Airnote project relies upon.
* Add `isValidDeviceUID()` function to check the validity of every device UID supplied to any Notehub API request function before the API call is made and abort the call if the deviceUID doesn't match the regex (note: `dev:`, `imei:`, `test:`, and `id:` are all valid prefixes)
n/a
Tests continue to pass.
1. In the `notehub.ts` file, try hardcoding a device UID inside of the `getDeviceEnvironmentVariables()` function. 
2. Any device UID beginning with  `dev:`, `imei:`, `test:`, or `id:` should successfully make an API call to Notehub, even if the string of letters and characters isn't a …

fix: add regex validation to ignore any invalid device UIDs from making API calls to Notehub

---

src/lib/services/notehub.ts
src/routes/[deviceUID]/+page.server.ts
src/routes/[deviceUID]/dashboard/+page.server.ts
src/routes/api/download/+server.ts

In an effort to limit bad actors trying to hit the Notehub API with junk requests, I implemented error handling to log every time a bad device ID was passed to the API and abort the call before it happened.
This caused a lot of messages of invalid device IDs and errors to show up in our logs. This needs to be quieted down and even validate the inputs earlier when possible to reduce unnecessary function executions.
* Change all throw Error validations into console.warn instead
* Add validation of device IDs to pages where API functions are originally invoked to cut down even further of function calls
All tests still pass.
n/a
https://bluesinc.atlassian.net/jira/software/c/projects/BLUESDEV/b …

chore: quiet error logging for invalid device IDs

---

src/routes/[deviceUID]/DeviceSettings.svelte
src/routes/[deviceUID]/Slider.svelte
src/routes/[deviceUID]/dashboard/+page.server.ts
src/routes/[deviceUID]/dashboard/+page.svelte

Per internal discussions, revert the map view of the Airnote devices to display even when they are set to indoors. And provide extra context to help users understand what it means to set a device to "indoors".
* Undo logic to show/hide map based on device's `_air_indoors` environment variable setting.
* Add clarifying text to "Indoors" checkbox in device settings page to better clarify what it means to set a device to "indoors" status.
All tests pass 
n/a

chore: adjust text for indoor devices

---

src/lib/util/url.ts

A customer was unable to export data from their Airnotes in the Notehub UI.  When the Export button is used, it downloads a 0 KB file.
The issue stems from a malformed URL filter that directs a user from the Airnote dashboard to the Notehub UI that displays just that particular device's events.
* Adjust the `getNotehubEventsUrl()` function to strip down the supplied deviceUID which includes the prefix of `dev:` to just the bare numbers before passing to the URL string
Prod (broken URL redirect)
Local version (fixed URL redirect)
All tests pass 
1. Go to http://localhost:5173/dev:864475044215258/dashboard
2. Click on the `View live Airnote events on Notehub.io` link below the current readings section of the dashboard
3. See it …

bug: adjust Notehub URL to filter to events for certain device [HUB-916]

---

package-lock.json
package.json
src/lib/services/notehub.ts
src/routes/[deviceUID]/+page.server.ts

A user reported they were unable to update their Airnote device settings even though they have the PIN number required to access those settings. Debugging revealed that the Notehub JS API call to get environment variables by PIN now requires a valid product UID instead of a project UID. Adjust the code to account for this new requirement.
* Update Notehub JS API calls that deal with PIN numbers to also require valid product UID strings, and add validation function to check that product UID string matches valid prefix pattern
* Update Notehub JS API dependencies to stay current with latest version of Notehub JS library
n/a
All tests continue to pass
1. Scan the QR code of an Airnote device to be redirected to its set up page with a …

bug: update the device env var by pin APIs to use productIDs going forward [BLUESDEV-457]
